# Generated by Django 5.2.4 on 2025-07-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='photos',
            new_name='photo',
        ),
    ]
