# Generated by Django 5.2.4 on 2025-07-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_remove_tweet_likes_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
